// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H

enum layer_names {
	L_BASE,
	L_ALT,
	L_NUM,
	L_F,
	L_SYM,
	L_NAV
};

#define OS_LCTL OSM(MOD_LCTL)
#define OS_RCTL OSM(MOD_RCTL)
#define OS_LALT OSM(MOD_LALT)
#define OS_RALT OSM(MOD_RALT)
#define OS_LGUI OSM(MOD_LGUI)
#define OS_RGUI OSM(MOD_RGUI)

#define TAB_PRV G(S(KC_LBRC))
#define TAB_NXT G(S(KC_RBRC))
#define APP_MAN G(S(KC_ESC))

#define TH_1 LT(L_NUM, KC_BSPC)
#define TH_2 LT(L_ALT, KC_SPC)
#define TH_3 LT(L_SYM, KC_ENT)

#define TH_1A LT(L_F, KC_BSPC)
#define TH_2N LT(L_F, KC_SPC)
#define TH_2A LT(L_NAV, KC_SPC)
#define TH_3S LT(L_NAV, KC_ENT)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[L_BASE] = LAYOUT_12X4(
		KC_TAB,  KC_A,    KC_T,    KC_H,    KC_S,    KC_D,    KC_J,    KC_V,    KC_P,    KC_W,    KC_X,    KC_BSPC,
		KC_ESC,  KC_O,    KC_N,    KC_R,    KC_E,    KC_I,    KC_K,    KC_Y,    KC_G,    KC_B,    KC_DOT,  KC_ENT,
		KC_LSFT, KC_U,    KC_M,    KC_L,    KC_F,    KC_C,    KC_Q,    KC_Z,    KC_QUOT, KC_COMM, KC_SLSH, KC_RSFT,
		KC_LCTL, KC_LALT, KC_LGUI, TH_1,    TH_2,    TH_3,    TH_3,    TH_2,    TH_1,    KC_RGUI, KC_RALT, KC_RCTL
	),
	[L_ALT] = LAYOUT_12X4(
		KC_TAB,  KC_X,    KC_W,    KC_P,    KC_V,    KC_J,    KC_D,    KC_S,    KC_H,    KC_T,    KC_A,    KC_BSPC,
		KC_ESC,  KC_DOT,  KC_B,    KC_G,    KC_Y,    KC_K,    KC_I,    KC_E,    KC_R,    KC_N,    KC_O,    KC_ENT,
		KC_LSFT, KC_SLSH, KC_COMM, KC_QUOT, KC_Z,    KC_Q,    KC_C,    KC_F,    KC_L,    KC_M,    KC_U,    KC_RSFT,
		OS_LCTL, OS_LALT, OS_LGUI, TH_1A,   TH_2,    TH_3S,   TH_3,    TH_2,    TH_1,    OS_RGUI, OS_RALT, OS_RCTL
	),
	[L_NUM] = LAYOUT_12X4(
		KC_TAB,  KC_EQL,  KC_7,    KC_8,    KC_9,    KC_PLUS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_BSPC,
		KC_ESC,  KC_DOT,  KC_4,    KC_5,    KC_6,    KC_MINS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_ENT,
		KC_LSFT, KC_SLSH, KC_1,    KC_2,    KC_3,    KC_0,    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_RSFT,
		OS_LCTL, OS_LALT, OS_LGUI, TH_1,    TH_2N,   TH_3,    TH_3,    TH_2N,   TH_1,    OS_RGUI, OS_RALT, OS_RCTL
	),
	[L_F] = LAYOUT_12X4(
		KC_TAB,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_BSPC,
		KC_ESC,  KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_ENT,
		KC_LSFT, KC_F11,  KC_F12,  KC_F13,  KC_F14,  KC_F15,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_RSFT,
		OS_LCTL, OS_LALT, OS_LGUI, TH_1,    TH_2,    TH_3,    TH_3,    TH_2,    TH_1,    OS_RGUI, OS_RALT, OS_RCTL
	),
	[L_SYM] = LAYOUT_12X4(
		KC_GRV,  KC_LT,   KC_GT,   KC_LBRC, KC_RBRC, KC_AMPR, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_BSPC,
		KC_TILD, KC_LPRN, KC_RPRN, KC_LCBR, KC_RCBR, KC_SCLN, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_ENT,
		KC_LSFT, KC_SLSH, KC_BSLS, KC_MINS, KC_EQL,  KC_PIPE, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_RSFT,
		OS_LCTL, OS_LALT, OS_LGUI, TH_1,    TH_2,    TH_3S,   TH_3,    TH_2,    TH_1,    OS_RGUI, OS_RALT, OS_RCTL
	),
	[L_NAV] = LAYOUT_12X4(
		KC_TAB,  KC_VOLU, KC_HOME, KC_UP,   KC_END,  KC_PGUP, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_BSPC,
		KC_ENT,  KC_VOLD, KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_ENT,
		KC_LSFT, KC_MUTE, XXXXXXX, TAB_PRV, TAB_NXT, APP_MAN, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_RSFT,
		OS_LCTL, OS_LALT, OS_LGUI, TH_1,    TH_2,    TH_3,    TH_3,    TH_2,    TH_1,    OS_RGUI, OS_RALT, OS_RCTL
	)
};
